
spring:
  config:
    activate:
      on-profile: docker
  
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: gymandkhana
      username: admin
      password: password123
      authentication-database: admin

server:
  port: 8080

logging:
  level:
    com.gymandkhana: INFO
    root: INFO