server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: user-service

  data:
    mongodb:
      host: localhost
      port: 27017
      database: gymandkhana
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      authentication-database: admin

  security:
    user:
      name: admin
      password: admin

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.gymandkhana: DEBUG
    org.springframework.security: DEBUG
    org.springframework.data.mongodb: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

